name: edge_veda_example
description: Example app for Edge Veda SDK
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  edge_veda:
    path: ../
  ffi: ">=2.0.0 <2.1.0"
  cupertino_icons: ^1.0.6
  camera: ^0.11.0+2
  path_provider: ^2.1.0
  file_picker: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true

dependency_overrides:
  win32: ^5.10.0
  ffi: ^2.1.3
